### PR TITLE
Adds more emotion to the script (ಥ﹏ಥ)

### PR DESCRIPTION
**Pull request by arthurgouveia**
Added a few more faces to the current script.

### CODE REVIEW

**Comment by arthurgouveia** [comment]
Do you need to re-generate the workflow file?
I've overwritten mine here with the file and it does not have the latest ones added.

**Comment by zvaehn** [comment]
yop. Pull and replace the workflow. See here. 52ee35f

**Comment by zvaehn** [comment]
You can edit the current workflow files as shown here: 
screen shot 2015-09-14 at 19 11 39

**Comment by arthurgouveia** [comment]
Cool. I've opened a PR with the workflow already updated with the new ones, just in case. That's what I did, BTW.

Thanks.

**Pull request merged**
